#!/bin/sh
#
workdir=/home/pi/accel/hue-force
 
start() {
    cd $workdir
    python ./hueforce.py &
    echo "Hue Force started."
}
 
stop() {
    pid=`ps -ef | grep 'hueforce' | awk '{ print $2 }'`
    echo $pid
    kill $pid
    sleep 2
    echo "Hue Force killed."
}
 
case "$1" in
  start)
    start
    ;;
  stop)
    stop   
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: /etc/init.d/hueforce {start|stop|restart}"
    exit 1
esac
exit 0